version: "3.8"

services:

  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - backend

  # ✅ Keycloak stateful avec PostgreSQL
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME_STRICT: "false"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - backend

  keycloak-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_pgdata:/var/lib/postgresql/data
    networks:
      - backend

  # ✅ DB utilisateurs pour le microservice users
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/file
    networks:
      - backend
    command: server -dev

  vault-init:
    image: hashicorp/vault:latest
    depends_on:
      - vault
    entrypoint: ["/bin/sh", "-c", "sleep 5 && /vault/init.sh"]
    volumes:
      - ./vault/init.sh:/vault/init.sh
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    networks:
      - backend




  # ✅ Microservice auth-proxy
  auth-proxy:
    build: ./auth-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-proxy.rule=PathPrefix(`/api/auth`)"
      - "traefik.http.routers.auth-proxy.entrypoints=web"
      - "traefik.http.services.auth-proxy.loadbalancer.server.port=8000"

      # 🔁 On définit ici le middleware auth directement dans ce service
      - "traefik.http.middlewares.auth.forwardauth.address=http://auth-proxy:8000/v1/validate"
      - "traefik.http.middlewares.auth.forwardauth.trustforwardheader=true"
      - "traefik.http.middlewares.auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Username,X-User-Email"
    depends_on:
      - keycloak
      - postgres
      - vault
      - vault-init
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      keycloak_url: http://keycloak:8080
      postgres_db: users_db
      realm: djassa
      audience: djassa-client
      user_service_url: http://users:8000     
    networks:
      - backend

  # ✅ Microservice users
  users:
    build: ./users
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.users.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.users.entrypoints=web"
      - "traefik.http.routers.users.middlewares=auth@docker,strip-users@docker"
      - "traefik.http.middlewares.strip-users.stripPrefix.prefixes=/api/users"
      - "traefik.http.services.users.loadbalancer.server.port=8000"
    depends_on:
      - keycloak
      - postgres
      - vault
      - vault-init
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
      keycloak_url: http://keycloak:8080
      postgres_db: users_db
      realm: djassa
      audience: djassa-client
      user_service_url: http://users:8000
      
    networks:
      - backend

networks:
  backend:

volumes:
  pgdata:
  keycloak_pgdata:
  vault_data:
